from .four_decker_sniper import *
from .ten_shoot_in_row import *
from .first_hit import *
from .strategist import *
from .secrecy_ships import *
from .piooner import *
from .lone_hunter import *
from .opening_the_battle import *
from .perficionists import *